### PR TITLE
Add tcl-duktape to the project list

### PR DESCRIPTION
**Pull request by dbohdan**

### CODE REVIEW

**Comment by svaarala** [comment]
Could you open a pull on the main Duktape repo to add yourself to the AUTHORS.rst file (see CONTRIBUTING.md)?

**Comment by dbohdan** [comment]
Done! https://github.com/svaarala/duktape/pull/805/

**Comment by svaarala** [comment]
Thanks! Merged and will autodeploy later on :)

**Comment by dbohdan** [comment]
Great!

**Pull request merged**
