### PR TITLE
Duktape Bindings for Crystal

### PR DESCRIPTION
**Pull request by jessedoyle**
* Add the [`duktape.cr`](https://github.com/jessedoyle/duktape.cr) library that contains Duktape bindings for
  the [Crystal Programming Language](https://crystal-lang.org/) :gem:.

### CODE REVIEW

**Comment by svaarala** [comment]
Apologies for the long delay -- could you add yourself to svaarala/duktape AUTHORS.rst, see https://github.com/svaarala/duktape-wiki/blob/master/CONTRIBUTING.md.

**Comment by jessedoyle** [comment]
@svaarala - Based on the documentation it sounds like you'd like the change to the `AUTHORS.rst` file as a separate PR? Or should I add my name in this PR?

Either way works fine for me - just wanting to follow the correct process!

**Comment by jessedoyle** [comment]
Ahh - my mistake, the file is in the base repo. PR incoming!

**Comment by svaarala** [comment]
Thanks!

**Pull request merged**
