### PR TITLE
Add Howto for working with value stack types

### PR DESCRIPTION
**Pull request by svaarala**

### CODE REVIEW

**Comment by harold-b** [comment]
This [table](https://github.com/svaarala/duktape-wiki/blob/6fc95a3dda72d0483b6284e74d5b19f01b4c7d36/HowtoValueStackTypes.md) helps a lot. Easy to visualize and figure out how it works/what to use.

Looking at it this way it really seems something like `duk_get_xxx_default()` and `duk_require_xxx_default` would be fairly intuitive to use.

**Comment by harold-b** [comment]
I wasn't exactly sure I followed the other [thread ](https://github.com/svaarala/duktape/pull/1264) where you guys (@svaarala and @fatcerberus) discussed the behavior since it seemed to me exactly like `duk_require` since when '**default**' was mentioned I assumed the *implicit* default, and thus didn't quit get it :confused:.  But the table clarified things instantly.

**Comment by svaarala** [comment]
`duk_get_xxx_default()` and `duk_require_xxx_default()` would be pretty good names IMO except that they're a bit long for commonly needed calls.

Because of `luaL_optXXX()` naming `duk_require_xxx_default()` -> `duk_opt_xxx()` would make sense to me. Using that name but `duk_get_xxx_default()` for the API call in this pull would also be OK, but it'd be nice to find a good `duk_<something>_xxx()` style name for it too.

`duk_default_xxx()` seems a bit odd. I'll give it some thought.

**Comment by harold-b** [comment]
Yeah I agree they are too long. To me it would be the ideal (as I mentioned in the other thread 'with_default'), it seems to convey the purpose intuitively, but of course, way too long.

My 2 cents for `duk_opt` is simply that having barely touched the lua API, (only did so once years ago for a tiny bit), I wouldn't find it familiar, (so I'm only speaking for those of us that don't come from lua). I of course see the benefit it would provide in being consistent with the lua API. So my input here perhaps is meaningless.

I do like the idea of having the calls be short and concise with the`duk_xxx_<type>` pattern for both cases as well since it keeps the function name small, and as you mentioned, they are used a lot.

 And yes `duk_default` does seems odd. If something pops up in my head I'll bring the feedback.

**Comment by fatcerberus** [comment]
I don't have much practical experience with Lua either, but I will say that Duktape's similarities to Lua are what drew me to it, so keeping consistency there is appreciated nonetheless.

**Pull request merged**
